# Generated by Django 5.0.3 on 2024-03-19 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cambio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aprobacion',
            options={'verbose_name': 'Aprobacion', 'verbose_name_plural': 'Aprobaciones'},
        ),
        migrations.AlterModelOptions(
            name='control',
            options={'verbose_name': 'Control', 'verbose_name_plural': 'Controles'},
        ),
        migrations.AlterModelOptions(
            name='impacto',
            options={'verbose_name': 'Impacto', 'verbose_name_plural': 'Impactos'},
        ),
        migrations.AlterModelOptions(
            name='prioridad',
            options={'verbose_name': 'Prioridad', 'verbose_name_plural': 'Prioridades'},
        ),
        migrations.AlterModelOptions(
            name='solicitud',
            options={'verbose_name': 'Solicitud', 'verbose_name_plural': 'Solicitudes'},
        ),
    ]
