# Generated by Django 5.0.3 on 2024-03-20 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cambio', '0002_alter_aprobacion_options_alter_control_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='control',
            name='Solicitud',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cambio.solicitud'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='control',
            name='Supervisor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
