# Generated by Django 5.0.3 on 2024-03-20 20:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cambio', '0003_control_solicitud_control_supervisor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='control',
            name='Solicitud',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cambio.solicitud'),
        ),
        migrations.AlterField(
            model_name='control',
            name='Supervisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
