# Generated by Django 5.0.3 on 2024-03-20 20:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cambio', '0005_remove_aprobacion_firma'),
    ]

    operations = [
        migrations.AddField(
            model_name='aprobacion',
            name='Fecha',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
