# Generated by Django 5.0.3 on 2024-03-21 18:32

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cambio', '0006_aprobacion_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='control',
            name='Evidencias_Pruebas_Seguridad',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Text'),
        ),
    ]
