# Generated by Django 5.0.3 on 2024-03-21 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cambio', '0007_control_evidencias_pruebas_seguridad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_Departamento', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='control',
            name='Evidencias_Pruebas_Seguridad',
        ),
        migrations.AlterField(
            model_name='control',
            name='Departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cambio.departamento'),
        ),
    ]
