# Generated by Django 5.0.3 on 2024-03-21 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cambio', '0009_alter_control_departamento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='control',
            options={'verbose_name': 'Control de cambios', 'verbose_name_plural': 'Controles de cambios'},
        ),
        migrations.AlterModelOptions(
            name='departamento',
            options={'verbose_name': 'Departamento', 'verbose_name_plural': 'Departamento'},
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='Fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
