# Generated by Django 5.0.3 on 2024-03-21 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cambio', '0010_alter_control_options_alter_departamento_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='Fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
