# Generated by Django 5.0.3 on 2024-03-21 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cambio', '0011_alter_solicitud_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control',
            name='Fecha',
            field=models.DateField(),
        ),
    ]
