# Generated by Django 5.0.3 on 2024-03-21 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cambio', '0012_alter_control_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='control',
            name='Solicitud',
        ),
        migrations.DeleteModel(
            name='Solicitud',
        ),
    ]
