# Generated by Django 5.0.3 on 2024-03-22 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cambio', '0014_control_destinatarios_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control',
            name='Email',
            field=models.EmailField(max_length=254),
        ),
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=100)),
                ('posicion', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('numero_contacto', models.CharField(max_length=10)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cambio.departamento')),
            ],
            options={
                'verbose_name': 'Responsable',
                'verbose_name_plural': 'Responsable',
            },
        ),
    ]
