# Generated by Django 5.0.3 on 2024-03-22 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cambio', '0015_alter_control_email_responsable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='control',
            name='Departamento',
        ),
        migrations.RemoveField(
            model_name='control',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='control',
            name='Nombre_Completo',
        ),
        migrations.RemoveField(
            model_name='control',
            name='Numero_Contacto',
        ),
        migrations.RemoveField(
            model_name='control',
            name='Posicion',
        ),
        migrations.AddField(
            model_name='control',
            name='responsables',
            field=models.ManyToManyField(to='cambio.responsable'),
        ),
    ]
