# Generated by Django 5.0.3 on 2024-03-20 20:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('members', models.ManyToManyField(blank=True, related_name='email_groups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
